/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import javax.swing.JOptionPane;

/**
 *
 * @author Niyatipc
 */
public class AddAccountMenu extends javax.swing.JDialog {

    private Bank bank;
    private Customer customer;

    /**
     * Creates new form AddAccountMenu
     */
    public AddAccountMenu(java.awt.Frame parent, boolean modal,Bank bank) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.bank = bank;
        customer = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        ssnLabel = new javax.swing.JLabel();
        ssnField = new javax.swing.JTextField();
        initialDepositLabel = new javax.swing.JLabel();
        initialDepositField = new javax.swing.JTextField();
        accountTypeLabel = new javax.swing.JLabel();
        accountTypeField = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account Menu");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        firstNameLabel.setText("First Name:");
        getContentPane().add(firstNameLabel);
        getContentPane().add(firstNameField);

        lastNameLabel.setText("Last Name:");
        getContentPane().add(lastNameLabel);
        getContentPane().add(lastNameField);

        ssnLabel.setText("Unique Identity Number:");
        getContentPane().add(ssnLabel);
        getContentPane().add(ssnField);

        initialDepositLabel.setText("Initial Deposit:");
        getContentPane().add(initialDepositLabel);
        getContentPane().add(initialDepositField);

        accountTypeLabel.setText("Account Type:");
        getContentPane().add(accountTypeLabel);

        accountTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking", "Savings" }));
        getContentPane().add(accountTypeField);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        StringBuilder warnings = new StringBuilder();
        String firstName = "", lastName = "" ,ssn = "" ,depositString =  "";
        Double amount = 0.0;
        if(firstNameField.getText().isEmpty()){
            warnings.append("First Name must not be empty\n");
        }
        else{
            firstName = firstNameField.getText();
        }
        if(lastNameField.getText().isEmpty()){
            warnings.append("Last Name must not be empty\n");
        }
        else{
            lastName = lastNameField.getText();
        }
        if(!ssnField.getText().matches("(\\d{3}-?){2}\\d{4}+")){
           warnings.append("Unique Identity Number must be a 10-digit number of the format xxx-xxx-xxxx\n");
        }
        else{
            ssn = ssnField.getText().replace("-","");
        }
        if(initialDepositField.getText().isEmpty()){
            warnings.append("Initial Deposit must be entered");
        }
        else{
            try{
                amount = Double.parseDouble(initialDepositField.getText());
            }
            catch(NumberFormatException ex){
                warnings.append("Ïnitial Deposit must be a number");
            }
        }
        if(warnings.length() > 0)
            JOptionPane.showMessageDialog(this,warnings.toString(),"Input Warnings" ,JOptionPane.WARNING_MESSAGE);
        else
        {   Account account = null;
            if(accountTypeField.getSelectedItem().toString() == "Checking") //JOptionPane.showMessageDialog(this, firstName+"\n"+lastName+"\n"+ssn+"\n"+amount);
               if(amount >= 100){
                    account = new Checking(amount);
               }
               else{
                   warnings.append("Amount must be greater than Rs.100 for Checking Account");
               }
            else if(accountTypeField.getSelectedItem().toString() == "Savings")
                if(amount >= 50){
                    account = new Savings(amount);
               }
               else{
                   warnings.append("Amount must be greater than Rs.50 for Checking Account");
               }
            if(account != null){
                customer = new Customer(firstName, lastName, ssn, account);
                bank.addCustomer(customer);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,warnings.toString(),"Input Warnings" ,JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountTypeField;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField initialDepositField;
    private javax.swing.JLabel initialDepositLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField ssnField;
    private javax.swing.JLabel ssnLabel;
    // End of variables declaration//GEN-END:variables

    Customer getCustomer() {
        return customer; //To change body of generated methods, choose Tools | Templates.
    }
}
